### ISSUE TITLE
Conflict on timeLeft with BetterContracts on dedicated server

### ISSUE THREAD

**Issue by Sileo35** [Mmtrx/FS22_TransportMissions#1]
Hello,
First of all, thx for your mods.
I have a problem on dedicated server.
timeLeft is null then there is a GUI error when we active the details of BetterContracts in Contract Panel.
I have try to correct this ... but I'm a newbie in FS22 modding and I didn't find how to correct this.

D:/Data/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/gui.lua:306: attempt to perform arithmetic on field 'timeLeft' (a nil value)
2022-07-06 10:20 Error: Running LUA method 'mouseEvent'.
D:/Data/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/gui.lua:306: attempt to perform arithmetic on field 'timeLeft' (a nil value)
2022-07-06 10:20 Error: Running LUA method 'update'.

**Comment by Sileo35** [comment]
I'm not sure if the problem comes from TransportMissions or from BetterContracts.
I have post here because apparently the problem comes from the read of timeLeft in this part.

**Comment by Mmtrx** [comment]
Thank you for the report. Somehow I didn't get an e-mail alert for this, so I just now saw it. But I will look at the issue asap.

**Comment by Sileo35** [comment]
No problem.
Just to confirm you, the combination of BetterContracts and TransportMissions works on solo game but I only have this error on dedicated server.
(And sorry but I'm french then I can't switch to German :p)

**Comment by Mmtrx** [comment]
Has been resolved with [BetterContracts v1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4)
